#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e

npm run prod

git status --porcelain | cut -c 3- | while read -r line; do
    git add "$line";
done

if [ -n "$(git status --porcelain)" ]; then
    git commit -m "Assets recompiled for production"
fi
