#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

set -e

container_id=$(docker ps -q -f name=dcmp-public);

if [ ! "$container_id" ]; then
  echo "Docker Containers are not running. Use: 'docker compose up -d public'"
  exit 1;
fi

eval "docker exec -d $container_id npm run production --workspaces";

git restore --staged .

git status --porcelain | cut -c 3- | grep -E "^.public/" | while read -r line; do
    git add "$line";
done

if [ -n "$(git diff --name-only --cached)" ]; then
    git commit -m "Assets recompiled for production"
fi
